### ISSUE TITLE
El resto de los milestones hay que ordenarlo

### ISSUE THREAD

**Issue by JJ** [pablojjimenez/TFG#24]
Cada milestone debe:
1. Describir un producto mínimamente viable (e incremental desde el anterior)
2. Tener un orden determinado.
3. Desarrollarse en el orden indicado.

**Comment by pablojjimenez** [comment]
He determinado: 

0. Infraestructura
1. Almacenamiento y estructuración de los datos.
2. Interfaz de programación de aplicaciones.
3. Frontend.

**Comment by JJ** [comment]
Hay que ordenarlo de forma lógica, y de forma que cada uno 
1. Especifique un producto mínimamente viable
2. Represente un avance sobre el anterior, incluyéndolo

En todo caso, debes especificar más. Siempre tiene que quedar muy claro cuál es el PMV que se va a presentar, así como qué lo hace viable o no. Por ejemplo
1. En [el 0](https://github.com/pablojjimenez/TFG/milestone/1) debes aclarar qué es lo que lo hace viable. ¿Workflows de CI en verde? ¿Una cantidad de HUs para ir trabajando?
2. En [el 1](https://github.com/pablojjimenez/TFG/milestone/5) falta todo, y ni siquiera creo que "almacenamiento de los datos" pueda convertirse en un producto viable. Tienes que hacer un desarrollo por capas, con la lógica de negocio que vayas a incluir (procesamiento, scraping) incluido en una serie de clases que compilen y sean correctas

**Comment by pablojjimenez** [comment]
Creo que estoy confundiendo distintas etapas del trabajo con el concepto de mojón.
<ins>Milestones:</ins>
1. **Infraestructura**: Contiene las HU iniciales para definir los objetivos, usuarios ficticios e integración continua para la memoria.

2. **Interfaz de programación de aplicación (API)**: Contiene la estructura del modelo que representa la solución del problema y todas las operaciones posibles a realizar con ellas. Es la supondrá la capa de abstracción para acceder a los datos y que pueda ser utilizada por otros desarrolladores para construir aplicaciones con distintos objetivos.

3. **Frontend**: Creación de un sistema web que permita consumir el servicio anterior satisfaciendo las necesidades de mis usuarios ficticios.

Cada uno de los milestones anteriores se construyen sobre el anterior y su completitud satisface los objetivos del trabajo. (Agradezco una pequeña revisión de la organización @JJ)

**Comment by JJ** [comment]
Entre 1 y 2 tendrás que tener un modelo de datos, identificar las fuentes, mirar el estado del arte... Tienes que integrar la escritura del informe con el desarrollo.

**Comment by pablojjimenez** [comment]
Efectivaente en esa descripción de milestones, olvidé por completo el modelo de datos con el que vamos a trabajar.


0. <ins>Infraestructura:</ins> Contiene las HU iniciales para definir los objetivos, usuarios ficticios e integración continua para la memoria.

1. <ins>Modelo de datos:</ins> definición de las clases que conforman el dominio del problema, atendiendo al estado del arte.

2. <ins>Interfaz de programación de aplicación (API):</ins> Contiene la estructura del modelo que representa la solución del problema y todas las operaciones posibles a realizar con ellas. Supondrá la capa de abstracción para acceder a los datos y que pueda ser utilizada por otros desarrolladores para construir aplicaciones con distintos objetivos.

3. <ins>Frontend:</ins> Creación de un sistema web que permita consumir el servicio anterior satisfaciendo las necesidades de mis usuarios ficticios.

Cada uno de los milestones anteriores se construyen sobre el anterior y en todos hay que ir documentando las decisiones tomadas y su completitud satisface los objetivos del trabajo.
Con esta entrada actualizo los milestones del repositorio.
