### ISSUE TITLE
Explicar las fuentes de datos

### ISSUE THREAD

**Issue by pablojjimenez** [pablojjimenez/TFG#32]
En relación a la HU #14 quiero que se pueda leer especificado la procedencia de cada una de las fuentes y las variables existentes.
Fuentes primarias: INE, datos abiertos gob, ISCIII

**Comment by JJ** [comment]
Yo no pondría las HUs de tan bajo nivel. Con una HU para el tribunal puede ser suficiente, no hace falta que pongas todas y cada una de las cosas que son necesarias.
También incluye el contexto: el tribunal, en general, va a mirar el informe y la presentación, no el código. Los problemas se resolverán con inclusión de texto en el informe
