### ISSUE TITLE
Interfaz REST 

### ISSUE THREAD

**Issue by pablojjimenez** [pablojjimenez/TFG#63]
En aras de completar la HU #42 
Implementar una una interfaz de comunicación REST para poder usar el trabajo usando verbos HTTP.

**Comment by pablojjimenez** [comment]
Como se expresa en la HU #62 el usuario quiere poder utilizar este trabajo con un interfaz agnóstico sin necesidad de descagarselo en forma de biblioteca ni nada por el estilo. Para ello, se propone la implementación de un sistema REST.

**La programadora** espera dos prefijos URI:
1. `/data` de donde colgarán las distintas colecciones que tenemos.
  - `/data/ccaas`
  - `/data/diseases`
  -  `/data/ages-groups`
  - `/data/cie`
  - `/data/raziel`
2. `/managers` donde cuelgan los endpoints pertinentes para obtener gráficos y realizar la pequeña predicción
-  `/managers/deaths-predictor-chart`
-  `/managers/deaths-predictor`
-  `/managers/chart`

**Comment by JJ** [comment]
Un issue plantea un problema, no una tarea.

**Comment by JJ** [comment]
O solucionas la #42, o la #64. Es difícil que con un issue avances dos HUs diferentes.
