### ISSUE TITLE
Hay que justificar la elección de un gestor de tareas

### ISSUE THREAD

**Issue by JJ** [pablojjimenez/TFG#79]
Makefile no es el más adecuado, ni está instalado por omisión cuando tienes Python.

https://github.com/pablojjimenez/TFG/blob/4b67f3dd7fa80e1b8ac15aea72b20e58ac20cf8c/Makefile#L1

Hay que justificar la elección de cualquier gestor, y cambiar la decisión a `invoke` u otro más pythónico. También hay que añadir todas las tareas que haya, como lanzar el backend.

**Comment by pablojjimenez** [comment]
El Makefile solo lo uso para la CI relacionadas con la documentación y LaTex por eso no están todas las tareas,  como lanzar el backend.
Para eso estoy utilizando `taskipy` como task runner. En el fichero de Poetry se pueden ver las tareas definidias:
- lint
- test
- serve (para lanzar el backend) 

Por ahora no veo la necesidad de usar `invoke` u otros más complejos. Este simplemente cubre mis necesidades actuales.

**Comment by pablojjimenez** [comment]
Añadir tmb porque se empecé a usar `unittest` y cambié a `pytest`.
